version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-equaluser}:${POSTGRES_PASSWORD:-equalpass}@db:5432/${POSTGRES_DB:-equaldb}?schema=public
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-equaldb}
      POSTGRES_USER: ${POSTGRES_USER:-equaluser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-equalpass}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  pgdata:
