/**
 * Push notification texts in every language the app ships.
 *
 * Pushes used to be written inline in whichever language the author happened
 * to use: match and message pushes in English for everyone, Daily Match and
 * Vibe pushes in Russian for everyone. They are now rendered in the
 * recipient's interface language (User.locale, sent by the app).
 *
 * Each row follows KEYS order. `{name}` / `{hours}` are filled in by pushText().
 */

export const PUSH_KEYS = [
  'match_title', 'match_body',
  'msg_title', 'msg_voice', 'msg_photo', 'msg_gift', 'msg_new', 'someone',
  'dm_ready_title', 'dm_ready_body', 'dm_msg_title',
  'dm_unlocked_title', 'dm_unlocked_body', 'dm_expired_title', 'dm_expired_body',
  'dm_nudge_title', 'dm_nudge_body', 'dm_soon_title', 'dm_soon_body',
  'vibe_title', 'vibe_body',
  'ask_new_title', 'ask_new_body', 'ask_answer_title', 'ask_answer_body',
] as const;

export type PushKey = (typeof PUSH_KEYS)[number];

const ROWS: Record<string, string[]> = {
  en: [
    "It's a Match! 💜", 'You and {name} liked each other!',
    'New message from {name}', '🎤 Voice message', '📷 Photo', '🎁 Sent you a gift', 'New message', 'Someone',
    'Your Daily Match is ready!', 'Say hi — you have 24 hours', '{name} wrote to you',
    '❤️ Match unlocked!', 'The chat is now open for good', '💔 Match expired', 'A new match arrives tomorrow',
    "You haven't written to your match yet", '{hours} h left', '🔔 Daily Match in 5 minutes', "You're about to meet someone new",
    "What's your vibe today?", "Pick a vibe and we'll find a match to fit it",
    'New question! 💜', 'Someone wants to know you better', 'Your question got an answer! 🎉', '{name} replied to your question',
  ],
  ru: [
    'Это мэтч! 💜', 'Вы с {name} понравились друг другу!',
    'Новое сообщение от {name}', '🎤 Голосовое сообщение', '📷 Фото', '🎁 Вам подарок', 'Новое сообщение', 'Кто-то',
    'Твой Daily Match готов!', 'Знакомься — у вас 24 часа', '{name} написал(а) тебе',
    '❤️ Мэтч открыт!', 'Чат открыт навсегда', '💔 Мэтч истёк', 'Новый мэтч — завтра',
    'Ты ещё не написал(а) своему мэтчу', 'Осталось {hours} ч', '🔔 Daily Match через 5 минут', 'Скоро познакомишься с новым человеком',
    'Какой у тебя настрой сегодня?', 'Выбери вайб — подберём мэтч под него',
    'Новый вопрос! 💜', 'Кто-то хочет узнать тебя получше', 'На твой вопрос ответили! 🎉', '{name} ответил(а) на твой вопрос',
  ],
  uk: [
    'Це метч! 💜', 'Ви з {name} сподобалися одне одному!',
    'Нове повідомлення від {name}', '🎤 Голосове повідомлення', '📷 Фото', '🎁 Вам подарунок', 'Нове повідомлення', 'Хтось',
    'Твій Daily Match готовий!', 'Знайомся — у вас 24 години', '{name} написав(ла) тобі',
    '❤️ Метч відкрито!', 'Чат відкрито назавжди', '💔 Метч минув', 'Новий метч — завтра',
    'Ти ще не написав(ла) своєму метчу', 'Залишилось {hours} год', '🔔 Daily Match за 5 хвилин', 'Скоро познайомишся з новою людиною',
    'Який у тебе настрій сьогодні?', 'Обери вайб — підберемо метч під нього',
    'Нове питання! 💜', 'Хтось хоче дізнатися тебе краще', 'На твоє питання відповіли! 🎉', '{name} відповів(ла) на твоє питання',
  ],
  de: [
    "It's a Match! 💜", 'Du und {name} mögt euch!',
    'Neue Nachricht von {name}', '🎤 Sprachnachricht', '📷 Foto', '🎁 Du hast ein Geschenk bekommen', 'Neue Nachricht', 'Jemand',
    'Dein Daily Match ist da!', 'Sag Hallo — ihr habt 24 Stunden', '{name} hat dir geschrieben',
    '❤️ Match freigeschaltet!', 'Der Chat bleibt jetzt für immer offen', '💔 Match abgelaufen', 'Morgen kommt ein neues Match',
    'Du hast deinem Match noch nicht geschrieben', 'Noch {hours} Std.', '🔔 Daily Match in 5 Minuten', 'Gleich lernst du jemand Neues kennen',
    'Wie ist deine Stimmung heute?', 'Wähle einen Vibe — wir finden ein passendes Match',
    'Neue Frage! 💜', 'Jemand möchte dich besser kennenlernen', 'Deine Frage wurde beantwortet! 🎉', '{name} hat auf deine Frage geantwortet',
  ],
  es: [
    '¡Es un match! 💜', '¡A ti y a {name} os gustáis!',
    'Nuevo mensaje de {name}', '🎤 Mensaje de voz', '📷 Foto', '🎁 Te enviaron un regalo', 'Nuevo mensaje', 'Alguien',
    '¡Tu Daily Match está listo!', 'Salúdale: tenéis 24 horas', '{name} te escribió',
    '❤️ ¡Match desbloqueado!', 'El chat queda abierto para siempre', '💔 El match caducó', 'Mañana llega un nuevo match',
    'Aún no le has escrito a tu match', 'Quedan {hours} h', '🔔 Daily Match en 5 minutos', 'Estás a punto de conocer a alguien nuevo',
    '¿Cuál es tu vibra hoy?', 'Elige una vibra y te buscamos un match que encaje',
    '¡Nueva pregunta! 💜', 'Alguien quiere conocerte mejor', '¡Tu pregunta tiene respuesta! 🎉', '{name} respondió a tu pregunta',
  ],
  fr: [
    "C'est un match ! 💜", 'Vous vous plaisez, {name} et vous !',
    'Nouveau message de {name}', '🎤 Message vocal', '📷 Photo', '🎁 Vous avez reçu un cadeau', 'Nouveau message', "Quelqu'un",
    'Votre Daily Match est prêt !', 'Dites bonjour — vous avez 24 heures', '{name} vous a écrit',
    '❤️ Match débloqué !', 'La discussion reste ouverte pour de bon', '💔 Match expiré', 'Un nouveau match arrive demain',
    "Vous n'avez pas encore écrit à votre match", 'Encore {hours} h', '🔔 Daily Match dans 5 minutes', 'Vous allez rencontrer quelqu’un de nouveau',
    "Quelle est votre humeur aujourd'hui ?", 'Choisissez une humeur, on vous trouve un match assorti',
    'Nouvelle question ! 💜', "Quelqu'un veut mieux vous connaître", 'Votre question a une réponse ! 🎉', '{name} a répondu à votre question',
  ],
  pt: [
    'Deu match! 💜', 'Você e {name} se curtiram!',
    'Nova mensagem de {name}', '🎤 Mensagem de voz', '📷 Foto', '🎁 Você recebeu um presente', 'Nova mensagem', 'Alguém',
    'Seu Daily Match está pronto!', 'Diga oi — vocês têm 24 horas', '{name} escreveu para você',
    '❤️ Match desbloqueado!', 'O chat fica aberto para sempre', '💔 O match expirou', 'Um novo match chega amanhã',
    'Você ainda não escreveu para o seu match', 'Faltam {hours} h', '🔔 Daily Match em 5 minutos', 'Você vai conhecer alguém novo',
    'Qual é a sua vibe hoje?', 'Escolha uma vibe e encontramos um match que combine',
    'Nova pergunta! 💜', 'Alguém quer conhecer você melhor', 'Sua pergunta foi respondida! 🎉', '{name} respondeu à sua pergunta',
  ],
  it: [
    "È un match! 💜", 'Tu e {name} vi piacete!',
    'Nuovo messaggio da {name}', '🎤 Messaggio vocale', '📷 Foto', '🎁 Hai ricevuto un regalo', 'Nuovo messaggio', 'Qualcuno',
    'Il tuo Daily Match è pronto!', 'Saluta: avete 24 ore', '{name} ti ha scritto',
    '❤️ Match sbloccato!', 'La chat resta aperta per sempre', '💔 Match scaduto', 'Domani arriva un nuovo match',
    'Non hai ancora scritto al tuo match', 'Mancano {hours} h', '🔔 Daily Match tra 5 minuti', 'Stai per conoscere qualcuno di nuovo',
    'Che vibe hai oggi?', 'Scegli una vibe e troviamo un match adatto',
    'Nuova domanda! 💜', 'Qualcuno vuole conoscerti meglio', 'La tua domanda ha una risposta! 🎉', '{name} ha risposto alla tua domanda',
  ],
  pl: [
    'Jest match! 💜', 'Ty i {name} polubiliście się nawzajem!',
    'Nowa wiadomość od {name}', '🎤 Wiadomość głosowa', '📷 Zdjęcie', '🎁 Masz prezent', 'Nowa wiadomość', 'Ktoś',
    'Twój Daily Match jest gotowy!', 'Przywitaj się — macie 24 godziny', '{name} napisał(a) do ciebie',
    '❤️ Match odblokowany!', 'Czat jest teraz otwarty na zawsze', '💔 Match wygasł', 'Nowy match jutro',
    'Nie napisałeś(-aś) jeszcze do swojego matcha', 'Zostało {hours} godz.', '🔔 Daily Match za 5 minut', 'Zaraz poznasz kogoś nowego',
    'Jaki masz dziś nastrój?', 'Wybierz vibe — dobierzemy do niego matcha',
    'Nowe pytanie! 💜', 'Ktoś chce cię lepiej poznać', 'Ktoś odpowiedział na twoje pytanie! 🎉', '{name} odpowiedział(a) na twoje pytanie',
  ],
  nl: [
    "Het is een match! 💜", 'Jij en {name} vinden elkaar leuk!',
    'Nieuw bericht van {name}', '🎤 Spraakbericht', '📷 Foto', '🎁 Je hebt een cadeau gekregen', 'Nieuw bericht', 'Iemand',
    'Je Daily Match staat klaar!', 'Zeg hallo — jullie hebben 24 uur', '{name} heeft je geschreven',
    '❤️ Match ontgrendeld!', 'De chat blijft nu voorgoed open', '💔 Match verlopen', 'Morgen komt er een nieuwe match',
    'Je hebt je match nog niet geschreven', 'Nog {hours} u', '🔔 Daily Match over 5 minuten', 'Je gaat zo iemand nieuws ontmoeten',
    'Wat is je vibe vandaag?', 'Kies een vibe, dan zoeken we een match die past',
    'Nieuwe vraag! 💜', 'Iemand wil je beter leren kennen', 'Je vraag is beantwoord! 🎉', '{name} heeft je vraag beantwoord',
  ],
  sv: [
    'Det är en match! 💜', 'Du och {name} gillar varandra!',
    'Nytt meddelande från {name}', '🎤 Röstmeddelande', '📷 Foto', '🎁 Du har fått en gåva', 'Nytt meddelande', 'Någon',
    'Din Daily Match är klar!', 'Säg hej — ni har 24 timmar', '{name} har skrivit till dig',
    '❤️ Match upplåst!', 'Chatten är nu öppen för gott', '💔 Matchen har gått ut', 'En ny match kommer i morgon',
    'Du har inte skrivit till din match än', '{hours} tim kvar', '🔔 Daily Match om 5 minuter', 'Snart träffar du någon ny',
    'Vilken vibe har du i dag?', 'Välj en vibe så hittar vi en match som passar',
    'Ny fråga! 💜', 'Någon vill lära känna dig bättre', 'Din fråga har fått svar! 🎉', '{name} svarade på din fråga',
  ],
  da: [
    'Det er et match! 💜', 'Du og {name} kan lide hinanden!',
    'Ny besked fra {name}', '🎤 Talebesked', '📷 Foto', '🎁 Du har fået en gave', 'Ny besked', 'Nogen',
    'Dit Daily Match er klar!', 'Sig hej — I har 24 timer', '{name} har skrevet til dig',
    '❤️ Match låst op!', 'Chatten er nu åben for altid', '💔 Match udløbet', 'Et nyt match kommer i morgen',
    'Du har ikke skrevet til dit match endnu', '{hours} t tilbage', '🔔 Daily Match om 5 minutter', 'Du møder snart en ny person',
    'Hvad er din vibe i dag?', 'Vælg en vibe, så finder vi et match, der passer',
    'Nyt spørgsmål! 💜', 'Nogen vil gerne lære dig bedre at kende', 'Dit spørgsmål har fået svar! 🎉', '{name} har svaret på dit spørgsmål',
  ],
  no: [
    'Det er en match! 💜', 'Du og {name} liker hverandre!',
    'Ny melding fra {name}', '🎤 Talemelding', '📷 Bilde', '🎁 Du har fått en gave', 'Ny melding', 'Noen',
    'Din Daily Match er klar!', 'Si hei — dere har 24 timer', '{name} har skrevet til deg',
    '❤️ Match låst opp!', 'Chatten er nå åpen for godt', '💔 Matchen har utløpt', 'En ny match kommer i morgen',
    'Du har ikke skrevet til matchen din ennå', '{hours} t igjen', '🔔 Daily Match om 5 minutter', 'Snart møter du noen nye',
    'Hvilken vibe har du i dag?', 'Velg en vibe, så finner vi en match som passer',
    'Nytt spørsmål! 💜', 'Noen vil bli bedre kjent med deg', 'Spørsmålet ditt har fått svar! 🎉', '{name} svarte på spørsmålet ditt',
  ],
  fi: [
    'Se on match! 💜', 'Sinä ja {name} tykkäätte toisistanne!',
    'Uusi viesti käyttäjältä {name}', '🎤 Ääniviesti', '📷 Kuva', '🎁 Sait lahjan', 'Uusi viesti', 'Joku',
    'Daily Matchisi on valmis!', 'Sano hei — teillä on 24 tuntia', '{name} kirjoitti sinulle',
    '❤️ Match avattu!', 'Keskustelu on nyt auki pysyvästi', '💔 Match vanhentui', 'Uusi match tulee huomenna',
    'Et ole vielä kirjoittanut matchillesi', '{hours} h jäljellä', '🔔 Daily Match 5 minuutin päästä', 'Tapaat pian jonkun uuden',
    'Millainen fiilis sinulla on tänään?', 'Valitse fiilis, niin etsimme siihen sopivan matchin',
    'Uusi kysymys! 💜', 'Joku haluaa tutustua sinuun paremmin', 'Kysymykseesi vastattiin! 🎉', '{name} vastasi kysymykseesi',
  ],
  cs: [
    'Je to match! 💜', 'Ty a {name} se líbíte!',
    'Nová zpráva od {name}', '🎤 Hlasová zpráva', '📷 Fotka', '🎁 Máš dárek', 'Nová zpráva', 'Někdo',
    'Tvůj Daily Match je připravený!', 'Pozdrav — máte 24 hodin', '{name} ti napsal(a)',
    '❤️ Match odemčen!', 'Chat je teď otevřený navždy', '💔 Match vypršel', 'Nový match přijde zítra',
    'Ještě jsi nenapsal(a) svému matchi', 'Zbývá {hours} h', '🔔 Daily Match za 5 minut', 'Za chvíli poznáš někoho nového',
    'Jakou máš dnes náladu?', 'Vyber si vibe a najdeme k němu match',
    'Nová otázka! 💜', 'Někdo tě chce lépe poznat', 'Na tvou otázku přišla odpověď! 🎉', '{name} odpověděl(a) na tvou otázku',
  ],
  el: [
    'Έχεις match! 💜', 'Εσύ και ο/η {name} αρέσετε ο ένας στον άλλον!',
    'Νέο μήνυμα από {name}', '🎤 Φωνητικό μήνυμα', '📷 Φωτογραφία', '🎁 Σου έστειλαν δώρο', 'Νέο μήνυμα', 'Κάποιος',
    'Το Daily Match σου είναι έτοιμο!', 'Πες ένα γεια — έχετε 24 ώρες', 'Ο/Η {name} σου έγραψε',
    '❤️ Το match ξεκλειδώθηκε!', 'Η συνομιλία μένει πλέον ανοιχτή', '💔 Το match έληξε', 'Νέο match έρχεται αύριο',
    'Δεν έχεις γράψει ακόμα στο match σου', 'Απομένουν {hours} ώρες', '🔔 Daily Match σε 5 λεπτά', 'Σε λίγο θα γνωρίσεις κάποιον νέο',
    'Τι διάθεση έχεις σήμερα;', 'Διάλεξε vibe και θα βρούμε match που ταιριάζει',
    'Νέα ερώτηση! 💜', 'Κάποιος θέλει να σε γνωρίσει καλύτερα', 'Η ερώτησή σου απαντήθηκε! 🎉', 'Ο/Η {name} απάντησε στην ερώτησή σου',
  ],
  tr: [
    'Eşleştiniz! 💜', 'Sen ve {name} birbirinizi beğendiniz!',
    '{name} kişisinden yeni mesaj', '🎤 Sesli mesaj', '📷 Fotoğraf', '🎁 Sana hediye gönderildi', 'Yeni mesaj', 'Biri',
    'Daily Match’in hazır!', 'Merhaba de — 24 saatiniz var', '{name} sana yazdı',
    '❤️ Eşleşme açıldı!', 'Sohbet artık kalıcı olarak açık', '💔 Eşleşmenin süresi doldu', 'Yeni eşleşme yarın geliyor',
    'Eşleşmene henüz yazmadın', '{hours} saat kaldı', '🔔 Daily Match 5 dakika sonra', 'Birazdan yeni biriyle tanışacaksın',
    'Bugün modun nasıl?', 'Bir mod seç, sana uygun bir eşleşme bulalım',
    'Yeni soru! 💜', 'Biri seni daha iyi tanımak istiyor', 'Soruna yanıt geldi! 🎉', '{name} sorunu yanıtladı',
  ],
  hu: [
    'Match! 💜', 'Te és {name} tetszetek egymásnak!',
    'Új üzenet tőle: {name}', '🎤 Hangüzenet', '📷 Fotó', '🎁 Ajándékot kaptál', 'Új üzenet', 'Valaki',
    'Elkészült a Daily Matched!', 'Köszönj — 24 órátok van', '{name} írt neked',
    '❤️ Match feloldva!', 'A csevegés mostantól végleg nyitva marad', '💔 A match lejárt', 'Holnap jön az új match',
    'Még nem írtál a matchednek', 'Még {hours} óra', '🔔 Daily Match 5 perc múlva', 'Mindjárt megismersz valakit',
    'Milyen a hangulatod ma?', 'Válassz hangulatot, és ahhoz illő matchet keresünk',
    'Új kérdés! 💜', 'Valaki jobban meg akar ismerni', 'Válasz érkezett a kérdésedre! 🎉', '{name} válaszolt a kérdésedre',
  ],
  ro: [
    'E un match! 💜', 'Tu și {name} vă plăceți!',
    'Mesaj nou de la {name}', '🎤 Mesaj vocal', '📷 Fotografie', '🎁 Ai primit un cadou', 'Mesaj nou', 'Cineva',
    'Daily Match-ul tău e gata!', 'Salută — aveți 24 de ore', '{name} ți-a scris',
    '❤️ Match deblocat!', 'Conversația rămâne deschisă definitiv', '💔 Match-ul a expirat', 'Un nou match vine mâine',
    'Încă nu i-ai scris match-ului tău', 'Mai sunt {hours} h', '🔔 Daily Match în 5 minute', 'Urmează să cunoști pe cineva nou',
    'Ce stare ai azi?', 'Alege o stare și îți găsim un match potrivit',
    'Întrebare nouă! 💜', 'Cineva vrea să te cunoască mai bine', 'Întrebarea ta a primit un răspuns! 🎉', '{name} ți-a răspuns la întrebare',
  ],
  hr: [
    'Imaš match! 💜', 'Ti i {name} sviđate se jedno drugome!',
    'Nova poruka od {name}', '🎤 Glasovna poruka', '📷 Fotografija', '🎁 Stigao ti je poklon', 'Nova poruka', 'Netko',
    'Tvoj Daily Match je spreman!', 'Pozdravi — imate 24 sata', '{name} ti je pisao/la',
    '❤️ Match otključan!', 'Razgovor je sada trajno otvoren', '💔 Match je istekao', 'Novi match stiže sutra',
    'Još nisi pisao/la svom matchu', 'Još {hours} h', '🔔 Daily Match za 5 minuta', 'Uskoro upoznaješ nekoga novog',
    'Kakvo ti je danas raspoloženje?', 'Odaberi vibe, a mi ćemo naći match koji mu odgovara',
    'Novo pitanje! 💜', 'Netko te želi bolje upoznati', 'Na tvoje pitanje stigao je odgovor! 🎉', '{name} je odgovorio/la na tvoje pitanje',
  ],
  id: [
    'Kalian match! 💜', 'Kamu dan {name} saling suka!',
    'Pesan baru dari {name}', '🎤 Pesan suara', '📷 Foto', '🎁 Kamu dapat hadiah', 'Pesan baru', 'Seseorang',
    'Daily Match kamu sudah siap!', 'Sapa dia — kalian punya 24 jam', '{name} mengirimimu pesan',
    '❤️ Match terbuka!', 'Obrolan kini terbuka selamanya', '💔 Match kedaluwarsa', 'Match baru datang besok',
    'Kamu belum menulis ke match-mu', 'Tersisa {hours} jam', '🔔 Daily Match 5 menit lagi', 'Sebentar lagi kamu bertemu orang baru',
    'Apa vibe kamu hari ini?', 'Pilih vibe dan kami carikan match yang cocok',
    'Pertanyaan baru! 💜', 'Seseorang ingin mengenalmu lebih dekat', 'Pertanyaanmu dijawab! 🎉', '{name} menjawab pertanyaanmu',
  ],
  ms: [
    'Anda sepadan! 💜', 'Anda dan {name} saling suka!',
    'Mesej baharu daripada {name}', '🎤 Mesej suara', '📷 Foto', '🎁 Anda menerima hadiah', 'Mesej baharu', 'Seseorang',
    'Daily Match anda sudah sedia!', 'Tegurlah — anda ada 24 jam', '{name} menulis kepada anda',
    '❤️ Padanan dibuka!', 'Sembang kini dibuka selama-lamanya', '💔 Padanan tamat tempoh', 'Padanan baharu tiba esok',
    'Anda belum menulis kepada padanan anda', 'Tinggal {hours} jam', '🔔 Daily Match dalam 5 minit', 'Anda bakal bertemu seseorang yang baharu',
    'Apakah vibe anda hari ini?', 'Pilih vibe dan kami carikan padanan yang sesuai',
    'Soalan baharu! 💜', 'Seseorang ingin mengenali anda dengan lebih dekat', 'Soalan anda telah dijawab! 🎉', '{name} menjawab soalan anda',
  ],
  fil: [
    "It's a Match! 💜", 'Nagustuhan ninyo ni {name} ang isa’t isa!',
    'Bagong mensahe mula kay {name}', '🎤 Voice message', '📷 Larawan', '🎁 Nakatanggap ka ng regalo', 'Bagong mensahe', 'May isang tao',
    'Handa na ang iyong Daily Match!', 'Mag-hi ka — may 24 oras kayo', 'Nag-message sa iyo si {name}',
    '❤️ Na-unlock ang match!', 'Bukas na ang chat magpakailanman', '💔 Nag-expire ang match', 'Darating bukas ang bagong match',
    'Hindi ka pa nagme-message sa iyong match', '{hours} oras na lang', '🔔 Daily Match sa loob ng 5 minuto', 'Malapit mo nang makilala ang isang bagong tao',
    'Ano ang vibe mo ngayon?', 'Pumili ng vibe at hahanapan ka namin ng match na bagay dito',
    'Bagong tanong! 💜', 'May gustong makakilala sa iyo nang mas mabuti', 'May sagot na ang tanong mo! 🎉', 'Sinagot ni {name} ang tanong mo',
  ],
  vi: [
    'Tương hợp rồi! 💜', 'Bạn và {name} đã thích nhau!',
    'Tin nhắn mới từ {name}', '🎤 Tin nhắn thoại', '📷 Ảnh', '🎁 Bạn nhận được một món quà', 'Tin nhắn mới', 'Ai đó',
    'Daily Match của bạn đã sẵn sàng!', 'Chào nhau đi — hai bạn có 24 giờ', '{name} đã nhắn cho bạn',
    '❤️ Đã mở khóa ghép đôi!', 'Cuộc trò chuyện giờ được mở mãi mãi', '💔 Ghép đôi đã hết hạn', 'Ngày mai sẽ có ghép đôi mới',
    'Bạn chưa nhắn cho người được ghép đôi', 'Còn {hours} giờ', '🔔 Daily Match sau 5 phút', 'Bạn sắp gặp một người mới',
    'Hôm nay tâm trạng của bạn thế nào?', 'Chọn một vibe, chúng tôi sẽ tìm người hợp với nó',
    'Câu hỏi mới! 💜', 'Có người muốn hiểu bạn hơn', 'Câu hỏi của bạn đã được trả lời! 🎉', '{name} đã trả lời câu hỏi của bạn',
  ],
  th: [
    'แมตช์แล้ว! 💜', 'คุณกับ {name} ถูกใจกันและกัน!',
    'ข้อความใหม่จาก {name}', '🎤 ข้อความเสียง', '📷 รูปภาพ', '🎁 คุณได้รับของขวัญ', 'ข้อความใหม่', 'ใครบางคน',
    'Daily Match ของคุณพร้อมแล้ว!', 'ทักทายกันเลย — คุณมีเวลา 24 ชั่วโมง', '{name} ส่งข้อความถึงคุณ',
    '❤️ ปลดล็อกแมตช์แล้ว!', 'แชทเปิดถาวรแล้ว', '💔 แมตช์หมดอายุ', 'แมตช์ใหม่จะมาพรุ่งนี้',
    'คุณยังไม่ได้ทักแมตช์ของคุณ', 'เหลืออีก {hours} ชม.', '🔔 Daily Match อีก 5 นาที', 'อีกไม่นานคุณจะได้รู้จักคนใหม่',
    'วันนี้คุณรู้สึกแบบไหน?', 'เลือกไวบ์ แล้วเราจะหาแมตช์ที่เข้ากันให้',
    'คำถามใหม่! 💜', 'มีคนอยากรู้จักคุณมากขึ้น', 'คำถามของคุณได้รับคำตอบแล้ว! 🎉', '{name} ตอบคำถามของคุณแล้ว',
  ],
  zh: [
    '配对成功！💜', '你和 {name} 互相喜欢！',
    '来自 {name} 的新消息', '🎤 语音消息', '📷 照片', '🎁 你收到了一份礼物', '新消息', '某人',
    '你的 Daily Match 已就绪！', '打个招呼吧——你们有 24 小时', '{name} 给你发了消息',
    '❤️ 配对已解锁！', '聊天现已永久开放', '💔 配对已过期', '明天会有新的配对',
    '你还没给你的配对发消息', '还剩 {hours} 小时', '🔔 Daily Match 还有 5 分钟', '你即将认识一个新朋友',
    '你今天的心情如何？', '选一个心情，我们为你匹配合适的人',
    '新问题！💜', '有人想更了解你', '你的问题有人回答了！🎉', '{name} 回答了你的问题',
  ],
  ja: [
    'マッチしました！💜', 'あなたと{name}さんがお互いにいいねしました！',
    '{name}さんから新しいメッセージ', '🎤 ボイスメッセージ', '📷 写真', '🎁 ギフトが届きました', '新しいメッセージ', '誰か',
    'Daily Matchの準備ができました！', 'あいさつしましょう — 24時間あります', '{name}さんからメッセージが届きました',
    '❤️ マッチが解放されました！', 'チャットはずっと開いたままになります', '💔 マッチの期限が切れました', '明日新しいマッチが届きます',
    'まだマッチ相手にメッセージを送っていません', '残り{hours}時間', '🔔 Daily Matchまであと5分', 'まもなく新しい人と出会えます',
    '今日の気分は？', '気分を選ぶと、それに合うマッチを探します',
    '新しい質問！💜', 'あなたのことをもっと知りたい人がいます', '質問に回答が届きました！🎉', '{name}さんがあなたの質問に答えました',
  ],
  ko: [
    '매칭 성공! 💜', '당신과 {name}님이 서로 좋아요를 눌렀어요!',
    '{name}님의 새 메시지', '🎤 음성 메시지', '📷 사진', '🎁 선물이 도착했어요', '새 메시지', '누군가',
    'Daily Match가 준비됐어요!', '인사해 보세요 — 24시간이 있어요', '{name}님이 메시지를 보냈어요',
    '❤️ 매칭이 열렸어요!', '이제 채팅이 계속 열려 있어요', '💔 매칭이 만료됐어요', '내일 새 매칭이 도착해요',
    '아직 매칭 상대에게 메시지를 보내지 않았어요', '{hours}시간 남음', '🔔 Daily Match 5분 전', '곧 새로운 사람을 만나요',
    '오늘 기분은 어때요?', '바이브를 고르면 어울리는 상대를 찾아 드려요',
    '새 질문! 💜', '누군가 당신을 더 알고 싶어해요', '질문에 답변이 달렸어요! 🎉', '{name}님이 질문에 답했어요',
  ],
  ar: [
    'حصل تطابق! 💜', 'أُعجبتَ أنت و{name} ببعضكما!',
    'رسالة جديدة من {name}', '🎤 رسالة صوتية', '📷 صورة', '🎁 وصلتك هدية', 'رسالة جديدة', 'شخص ما',
    'تطابقك اليومي جاهز!', 'قل مرحبًا — لديكما 24 ساعة', 'راسلك {name}',
    '❤️ تم فتح التطابق!', 'أصبحت المحادثة مفتوحة للأبد', '💔 انتهى التطابق', 'تطابق جديد يصل غدًا',
    'لم تراسل تطابقك بعد', 'بقي {hours} ساعة', '🔔 التطابق اليومي بعد 5 دقائق', 'ستتعرف قريبًا على شخص جديد',
    'ما مزاجك اليوم؟', 'اختر مزاجك وسنجد لك تطابقًا يناسبه',
    'سؤال جديد! 💜', 'شخص ما يريد أن يعرفك أكثر', 'تلقى سؤالك إجابة! 🎉', 'أجاب {name} على سؤالك',
  ],
  he: [
    'יש התאמה! 💜', 'את/ה ו{name} אהבתם זה את זה!',
    'הודעה חדשה מ{name}', '🎤 הודעה קולית', '📷 תמונה', '🎁 קיבלת מתנה', 'הודעה חדשה', 'מישהו',
    'ה-Daily Match שלך מוכן!', 'תגידו שלום — יש לכם 24 שעות', '{name} כתב/ה לך',
    '❤️ ההתאמה נפתחה!', 'הצ׳אט פתוח עכשיו לתמיד', '💔 ההתאמה פגה', 'התאמה חדשה תגיע מחר',
    'עוד לא כתבת להתאמה שלך', 'נשארו {hours} שעות', '🔔 Daily Match בעוד 5 דקות', 'עוד רגע תכירו מישהו חדש',
    'מה הווייב שלך היום?', 'בחר/י ווייב ונמצא התאמה שמתאימה לו',
    'שאלה חדשה! 💜', 'מישהו רוצה להכיר אותך טוב יותר', 'השאלה שלך קיבלה תשובה! 🎉', '{name} ענה/תה על השאלה שלך',
  ],
  fa: [
    'مچ شدید! 💜', 'شما و {name} از هم خوشتان آمد!',
    'پیام جدید از {name}', '🎤 پیام صوتی', '📷 عکس', '🎁 یک هدیه دریافت کردید', 'پیام جدید', 'کسی',
    'Daily Match شما آماده است!', 'سلام کنید — ۲۴ ساعت فرصت دارید', '{name} به شما پیام داد',
    '❤️ مچ باز شد!', 'گفتگو اکنون برای همیشه باز است', '💔 مچ منقضی شد', 'مچ جدید فردا می‌رسد',
    'هنوز به مچ خود پیام نداده‌اید', '{hours} ساعت باقی مانده', '🔔 Daily Match تا ۵ دقیقه دیگر', 'به‌زودی با فرد جدیدی آشنا می‌شوید',
    'امروز حال‌وهوایتان چطور است؟', 'یک حال‌وهوا انتخاب کنید تا مچ مناسبش را پیدا کنیم',
    'سؤال جدید! 💜', 'کسی می‌خواهد شما را بهتر بشناسد', 'به سؤال شما پاسخ داده شد! 🎉', '{name} به سؤال شما پاسخ داد',
  ],
  hi: [
    'मैच हो गया! 💜', 'आप और {name} ने एक-दूसरे को पसंद किया!',
    '{name} का नया संदेश', '🎤 वॉइस संदेश', '📷 फ़ोटो', '🎁 आपको एक उपहार मिला', 'नया संदेश', 'कोई',
    'आपका Daily Match तैयार है!', 'हाय कहिए — आपके पास 24 घंटे हैं', '{name} ने आपको संदेश भेजा',
    '❤️ मैच अनलॉक हुआ!', 'चैट अब हमेशा के लिए खुली है', '💔 मैच की अवधि समाप्त', 'नया मैच कल आएगा',
    'आपने अभी तक अपने मैच को संदेश नहीं भेजा', '{hours} घंटे बाकी', '🔔 Daily Match 5 मिनट में', 'जल्द ही आप किसी नए व्यक्ति से मिलेंगे',
    'आज आपका मूड कैसा है?', 'एक वाइब चुनें, हम उसके हिसाब से मैच ढूंढेंगे',
    'नया सवाल! 💜', 'कोई आपको बेहतर जानना चाहता है', 'आपके सवाल का जवाब आया! 🎉', '{name} ने आपके सवाल का जवाब दिया',
  ],
  bn: [
    'ম্যাচ হয়েছে! 💜', 'আপনি আর {name} একে অপরকে পছন্দ করেছেন!',
    '{name}-এর নতুন বার্তা', '🎤 ভয়েস বার্তা', '📷 ছবি', '🎁 আপনি একটি উপহার পেয়েছেন', 'নতুন বার্তা', 'কেউ',
    'আপনার Daily Match তৈরি!', 'হাই বলুন — আপনাদের হাতে ২৪ ঘণ্টা', '{name} আপনাকে বার্তা পাঠিয়েছেন',
    '❤️ ম্যাচ আনলক হয়েছে!', 'চ্যাট এখন চিরদিনের জন্য খোলা', '💔 ম্যাচের মেয়াদ শেষ', 'নতুন ম্যাচ আসবে আগামীকাল',
    'আপনি এখনও আপনার ম্যাচকে লেখেননি', '{hours} ঘণ্টা বাকি', '🔔 Daily Match ৫ মিনিট পরে', 'শিগগিরই আপনি নতুন কারও সঙ্গে পরিচিত হবেন',
    'আজ আপনার মুড কেমন?', 'একটি ভাইব বেছে নিন, আমরা মানানসই ম্যাচ খুঁজে দেব',
    'নতুন প্রশ্ন! 💜', 'কেউ আপনাকে আরও ভালো করে জানতে চায়', 'আপনার প্রশ্নের উত্তর এসেছে! 🎉', '{name} আপনার প্রশ্নের উত্তর দিয়েছেন',
  ],
  ta: [
    'மேட்ச் ஆனது! 💜', 'நீங்களும் {name}-உம் ஒருவரையொருவர் விரும்பினீர்கள்!',
    '{name}-இடமிருந்து புதிய செய்தி', '🎤 குரல் செய்தி', '📷 புகைப்படம்', '🎁 உங்களுக்கு ஒரு பரிசு வந்துள்ளது', 'புதிய செய்தி', 'யாரோ',
    'உங்கள் Daily Match தயார்!', 'வணக்கம் சொல்லுங்கள் — உங்களுக்கு 24 மணிநேரம் உள்ளது', '{name} உங்களுக்கு எழுதியுள்ளார்',
    '❤️ மேட்ச் திறக்கப்பட்டது!', 'அரட்டை இப்போது நிரந்தரமாகத் திறந்துள்ளது', '💔 மேட்ச் காலாவதியானது', 'புதிய மேட்ச் நாளை வரும்',
    'உங்கள் மேட்சுக்கு இன்னும் எழுதவில்லை', '{hours} மணிநேரம் மீதம்', '🔔 Daily Match 5 நிமிடங்களில்', 'விரைவில் ஒரு புதிய நபரைச் சந்திப்பீர்கள்',
    'இன்று உங்கள் மனநிலை என்ன?', 'ஒரு வைப் தேர்ந்தெடுங்கள், அதற்கேற்ற மேட்சைக் கண்டுபிடிப்போம்',
    'புதிய கேள்வி! 💜', 'யாரோ உங்களை நன்கு அறிய விரும்புகிறார்', 'உங்கள் கேள்விக்குப் பதில் வந்தது! 🎉', '{name} உங்கள் கேள்விக்குப் பதிலளித்தார்',
  ],
  sw: [
    'Mmelingana! 💜', 'Wewe na {name} mmependana!',
    'Ujumbe mpya kutoka kwa {name}', '🎤 Ujumbe wa sauti', '📷 Picha', '🎁 Umepokea zawadi', 'Ujumbe mpya', 'Mtu fulani',
    'Daily Match yako iko tayari!', 'Msalimie — mna saa 24', '{name} amekuandikia',
    '❤️ Mlingano umefunguliwa!', 'Gumzo sasa liko wazi milele', '💔 Mlingano umeisha muda', 'Mlingano mpya unakuja kesho',
    'Bado hujamwandikia mlingano wako', 'Zimebaki saa {hours}', '🔔 Daily Match baada ya dakika 5', 'Karibu utakutana na mtu mpya',
    'Hali yako leo ikoje?', 'Chagua vibe nasi tutakutafutia mlingano unaofaa',
    'Swali jipya! 💜', 'Mtu anataka kukufahamu zaidi', 'Swali lako limejibiwa! 🎉', '{name} amejibu swali lako',
  ],
};

export const PUSH_LOCALES = Object.keys(ROWS);

/** Render a push text in `locale`, falling back to English. */
export function pushText(locale: string | null | undefined, key: PushKey, params: Record<string, string | number> = {}): string {
  const row = ROWS[locale && ROWS[locale] ? locale : 'en'];
  const template = row[PUSH_KEYS.indexOf(key)] ?? ROWS.en[PUSH_KEYS.indexOf(key)];
  return template.replace(/\{(\w+)\}/g, (_, p: string) => String(params[p] ?? ''));
}
